FROM node:19
WORKDIR /usr/src/app
RUN npm install -g @vue/cli
# WORKDIR /app

# COPY Vue3/package*.json ./

# RUN npm install

# COPY Vue3 /app

# RUN npm run build

# ENTRYPOINT  ["npm", "run", "serve"]